/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import database.ConnectDB;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author My Laptop
 */
import javax.swing.table.DefaultTableModel;
public class KhachHangForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KhachHangForm.class.getName());

    /**
     * Creates new form KHACH_HANGFORM
     */
    int maKH;
    public KhachHangForm(int maKH) {
        initComponents();
        this.maKH = maKH;
        lblMaKH.setText("Mã KH: " +" "+ maKH);

    loadPhuongThuc();
    loadHoaDon(maKH);
    }
    public void loadHoaDon(int maKH){

    try{
        Connection conn = ConnectDB.getConnection();

        String sql = "SELECT MaHoaDon, ChiSoCu, ChiSoMoi, TrangThai, NgayThanhToan FROM HOA_DON WHERE MaKH=?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, maKH);

        ResultSet rs = ps.executeQuery();

        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);

        while(rs.next()){

            int soDien = rs.getInt("ChiSoMoi") - rs.getInt("ChiSoCu");

            model.addRow(new Object[]{
                rs.getInt("MaHoaDon"),
                soDien,
                rs.getInt("TrangThai") == 0 ? "Chưa thanh toán" : "Đã thanh toán",
                rs.getDate("NgayThanhToan")
            });
        }

    }catch(Exception e){
        e.printStackTrace();
    }
}
    public void loadPhuongThuc(){

    try{
        Connection conn = ConnectDB.getConnection();

        String sql = "SELECT MaPT, TenPT FROM PHUONG_THUC_THANH_TOAN";

        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        cboPhuongThuc.removeAllItems();

        while(rs.next()){
            int maPT = rs.getInt("MaPT");
            String tenPT = rs.getString("TenPT");

            // hiển thị dạng: 1 - Tiền mặt
            cboPhuongThuc.addItem(maPT + " - " + tenPT);
        }

    }catch(Exception e){
        e.printStackTrace();
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnThanhToan = new javax.swing.JButton();
        cboPhuongThuc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        lblMaKH = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.addActionListener(this::btnThanhToanActionPerformed);
        jPanel1.add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        cboPhuongThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Momo", "Mbbank", "Techcombank", "Zalopay", "TP bank", "VP bank", "Vietcombank", "ManhHungBank" }));
        jPanel1.add(cboPhuongThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 116, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Phương Thức Thanh Toán");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 211, -1, -1));

        tblHoaDon.setBackground(new java.awt.Color(204, 204, 204));
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaHD", "Số Điện", "Trạng Thái", "Ngày Thanh Toán"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 337));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Danh Sách Hóa Đơn");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(this::btnDangXuatActionPerformed);
        jPanel1.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        lblMaKH.setForeground(new java.awt.Color(255, 255, 255));
        lblMaKH.setText("MaKH :");
        jPanel1.add(lblMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 78, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HỆ THỐNG QUẢN LÝ KHÁCH HÀNG TIÊU THỤ ĐIỆN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/4.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 5, 500, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
       int row = tblHoaDon.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(this,"Chọn hóa đơn cần thanh toán");
        return;
    }

String trangThai = tblHoaDon.getValueAt(row, 2).toString();
String selected = cboPhuongThuc.getSelectedItem().toString();
int maPT = Integer.parseInt(selected.split(" - ")[0]);
    if(trangThai.equals("Đã thanh toán")){
        JOptionPane.showMessageDialog(this,"Hóa đơn này đã thanh toán rồi");
        return;
    }

    int MaHoaDon = Integer.parseInt(tblHoaDon.getValueAt(row, 0).toString());

    try{
        Connection conn = ConnectDB.getConnection();

        String sql = "UPDATE HOA_DON SET TrangThai=1, NgayThanhToan=GETDATE(), MaPT=? WHERE MaHoaDon=?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, maPT);
ps.setInt(2, MaHoaDon);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this,"Thanh toán thành công");

        loadHoaDon(maKH);

    }catch(Exception e){
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int chon = JOptionPane.showConfirmDialog(this,
            "Bạn có muốn đăng xuất không?");

    if (chon == JOptionPane.YES_OPTION) {

        LoginForm login = new LoginForm();
        login.setVisible(true);

        this.dispose(); 
    }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cboPhuongThuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JTable tblHoaDon;
    // End of variables declaration//GEN-END:variables
}
