/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import database.ConnectDB;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author My Laptop
 */
public class LichSuXoaTKForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LichSuXoaTKForm.class.getName());

    /**
     * Creates new form LichSuXoaTKForm
     */
    public LichSuXoaTKForm() {
        initComponents();
        loadTaiKhoanDaXoa();
    }
    public void loadTaiKhoanDaXoa(){

    DefaultTableModel model = (DefaultTableModel) tblTaiKhoan.getModel();
    model.setRowCount(0);

    try{
        Connection conn = ConnectDB.getConnection();

        String sql = "SELECT * FROM TAI_KHOAN WHERE TrangThai = 0 AND VAITRO != 0";

        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{
                rs.getInt("MaTK"),
                rs.getString("TenDangNhap"),
                rs.getString("MatKhau"),
                "Khách",
                rs.getObject("MaKH"),
                "Đã khóa"
            });

        }

    }catch(Exception e){
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnKhoiPhuc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 119, -1, -1));

        tblTaiKhoan.setBackground(new java.awt.Color(204, 204, 204));
        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MaTK", "Tên Đăng Nhập", "Mật Khẩu", "Vai Trò", "MaKH", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTaiKhoan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 375, 284));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN KHÁCH HÀNG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnKhoiPhuc.setText("Khôi phục");
        btnKhoiPhuc.addActionListener(this::btnKhoiPhucActionPerformed);
        getContentPane().add(btnKhoiPhuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Danh Sách Tài Khoản");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(this::btnThoatActionPerformed);
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/6.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhoiPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoiPhucActionPerformed
        int row = tblTaiKhoan.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(this,"Chọn tài khoản cần khôi phục");
        return;
    }

    int maTK = Integer.parseInt(tblTaiKhoan.getValueAt(row, 0).toString());

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc muốn khôi phục tài khoản này?",
        "Xác nhận",
        JOptionPane.YES_NO_OPTION
    );

    if(confirm != JOptionPane.YES_OPTION){
        return;
    }

    try{
        Connection conn = ConnectDB.getConnection();

        String sql = "UPDATE TAI_KHOAN SET TrangThai = 1 WHERE MaTK=?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, maTK);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this,"Khôi phục thành công");

        loadTaiKhoanDaXoa(); // reload lại

    }catch(Exception e){
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnKhoiPhucActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
       QLTaiKhoanForm f = new QLTaiKhoanForm();
       f .setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LichSuXoaTKForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhoiPhuc;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
