/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import javax.swing.JOptionPane;
import java.sql.*;
import database.ConnectDB;
import form.QLKhachHangForm;
/**
 *
 * @author My Laptop
 */
public class LoginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnhNen = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDangKy = new javax.swing.JButton();
        Anhnen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AnhNen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setBackground(new java.awt.Color(204, 255, 255));
        txtUser.addActionListener(this::txtUserActionPerformed);
        AnhNen.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 200, -1));

        btnLogin.setBackground(new java.awt.Color(204, 204, 204));
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Đăng Nhập");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        AnhNen.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        btnHuy.setBackground(new java.awt.Color(204, 204, 204));
        btnHuy.setForeground(new java.awt.Color(0, 0, 0));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(this::btnHuyActionPerformed);
        AnhNen.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));

        txtPass.setBackground(new java.awt.Color(204, 255, 255));
        txtPass.addActionListener(this::txtPassActionPerformed);
        AnhNen.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 200, -1));

        jLabel1.setBackground(new java.awt.Color(51, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Đăng Nhập");
        AnhNen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tên Đăng Nhập");
        AnhNen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mật Khẩu");
        AnhNen.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnDangKy.setBackground(new java.awt.Color(204, 204, 204));
        btnDangKy.setForeground(new java.awt.Color(0, 0, 0));
        btnDangKy.setText("Đăng Ký");
        btnDangKy.addActionListener(this::btnDangKyActionPerformed);
        AnhNen.add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        Anhnen.setBackground(new java.awt.Color(255, 255, 255));
        Anhnen.setForeground(new java.awt.Color(153, 153, 153));
        Anhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Đăng Nhập.png"))); // NOI18N
        AnhNen.add(Anhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnhNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AnhNen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed

    }//GEN-LAST:event_txtUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
      String user = txtUser.getText();
        String pass = txtPass.getText();

try{

    Connection conn = ConnectDB.getConnection();

    String sql = "SELECT * FROM TAI_KHOAN WHERE TenDangNhap=? AND MatKhau=?";

    PreparedStatement ps = conn.prepareStatement(sql);

    ps.setString(1,user);
    ps.setString(2,pass);

    ResultSet rs = ps.executeQuery();

    if(rs.next()){

        int vaitro = rs.getInt("VaiTro");
        int maKH = rs.getInt("MaKH");

        if(vaitro == 0){
            new AdminForm().setVisible(true);
        }else{
            new KhachHangForm(maKH).setVisible(true);
        }

        this.dispose();

    }else{
        JOptionPane.showMessageDialog(this,"Sai tài khoản hoặc mật khẩu");
    }

}catch(Exception e){
    e.printStackTrace();
}
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
    txtUser.setText("");
    txtPass.setText("");
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
      DangKyForm f = new DangKyForm();
      f.setVisible(true);
      this.dispose(); 
    }//GEN-LAST:event_btnDangKyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnhNen;
    private javax.swing.JLabel Anhnen;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
