/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import database.ConnectDB;
import javax.swing.JOptionPane;
/**
 *
 * @author My Laptop
 */
public class QLTaiKhoanForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QLTaiKhoanForm.class.getName());

    /**
     * Creates new form QLTaiKhoanForm
     */
    public QLTaiKhoanForm() {
        initComponents();
        loadTaiKhoan();
    }
    public void loadTaiKhoan(){

    DefaultTableModel model = (DefaultTableModel) tblTaiKhoan.getModel();
    model.setRowCount(0);

    try{
        Connection conn = ConnectDB.getConnection();

        String sql = "SELECT * FROM TAI_KHOAN WHERE TrangThai = 1 AND VAITRO != 0";

        PreparedStatement ps = conn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{
                rs.getInt("MaTK"),
                rs.getString("TenDangNhap"),
                rs.getString("MatKhau"),
                rs.getInt("VaiTro") == 0 ? "Admin" : "Khách",
                rs.getObject("MaKH"),
                "Hoạt động"
            });

        }

    }catch(Exception e){
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnXoa = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnLichSuXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(this::btnQuayLaiActionPerformed);
        getContentPane().add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        tblTaiKhoan.setBackground(new java.awt.Color(204, 204, 204));
        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MaTK", "Tên Đăng Nhập", "Mật Khẩu", "Vai Trò", "MaKH", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTaiKhoan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, 440, 301));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Danh Sách Tài Khoản");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        btnLichSuXoa.setText(" Lịch Sử Xóa TK");
        btnLichSuXoa.addActionListener(this::btnLichSuXoaActionPerformed);
        getContentPane().add(btnLichSuXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QUẢN LÝ TÀI KHOẢN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/5.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        AdminForm f = new AdminForm();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblTaiKhoan.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(this,"Chọn tài khoản cần xóa");
        return;
    }

    int maTK = Integer.parseInt(tblTaiKhoan.getValueAt(row, 0).toString());

    String vaiTro = tblTaiKhoan.getValueAt(row, 3).toString();

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc muốn xóa tài khoản này?",
        "Xác nhận",
        JOptionPane.YES_NO_OPTION
    );

    if(confirm != JOptionPane.YES_OPTION){
        return;
    }

    try{
        Connection conn = ConnectDB.getConnection();

        String sql = "UPDATE TAI_KHOAN SET TrangThai = 0 WHERE MaTK=?";

        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, maTK);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this,"Đã khóa tài khoản");

        loadTaiKhoan(); // reload lại bảng

    }catch(Exception e){
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLichSuXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLichSuXoaActionPerformed
       LichSuXoaTKForm f = new LichSuXoaTKForm();
       f .setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnLichSuXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QLTaiKhoanForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLichSuXoa;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
