/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;
import dao.Hoa_DonDAO;
import model.HOA_DON;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.TinhTienDien;
import javax.swing.JOptionPane;

/**
 *
 * @author My Laptop
 */
public class TaoHDForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TaoHDForm.class.getName());

    /**
     * Creates new form TaoHDForm
     */
    public TaoHDForm() {
        initComponents();
        loadHoaDon();
}
private void loadHoaDon() {

        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();

        model.setRowCount(0);
        Hoa_DonDAO dao = new Hoa_DonDAO();
        ArrayList<HOA_DON> list = dao.getAllHoaDon();

        for (HOA_DON hd : list) {

            int soDien = hd.getChiSoMoi() - hd.getChiSoCu();

            int soTien = TinhTienDien.tinhTienDien(soDien);

            model.addRow(new Object[]{
    hd.getMaHoaDon(), 
    hd.getMaKH(),
    hd.getChiSoCu(),
    hd.getChiSoMoi(),
    soDien,
    soTien
});

        }

    }

    private void clearForm() {

        txtMaKH.setText("");
        txtChiSoCu.setText("");
        txtChiSoMoi.setText("");

    }
private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {                                     
    int row = tblHoaDon.getSelectedRow();

    txtMaKH.setText(tblHoaDon.getValueAt(row,0).toString());
txtChiSoCu.setText(tblHoaDon.getValueAt(row,1).toString());
txtChiSoMoi.setText(tblHoaDon.getValueAt(row,2).toString());
}

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTaoHoaDon = new javax.swing.JButton();
        txtMaKH = new javax.swing.JTextField();
        txtChiSoCu = new javax.swing.JTextField();
        txtChiSoMoi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TẠO HÓA ĐƠN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 15, -1, 36));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MaKH :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 51, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chỉ Số Cũ :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 64, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Chỉ Số Mới :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 70, 20));

        btnTaoHoaDon.setText("Tạo hóa đơn");
        btnTaoHoaDon.addActionListener(this::btnTaoHoaDonActionPerformed);
        getContentPane().add(btnTaoHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtMaKH.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 57, 195, -1));

        txtChiSoCu.setBackground(new java.awt.Color(204, 204, 204));
        txtChiSoCu.addActionListener(this::txtChiSoCuActionPerformed);
        getContentPane().add(txtChiSoCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 110, 195, -1));

        txtChiSoMoi.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtChiSoMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 162, 195, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DANH SÁCH HÓA ĐƠN");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 263, -1, -1));

        tblHoaDon.setBackground(new java.awt.Color(204, 204, 204));
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MaHoaDon", "MaKH", "ChiSoCu", "ChiSoMoi", "SoDien", "SoTien"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 291, 375, 311));

        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(this::btnQuayLaiActionPerformed);
        getContentPane().add(btnQuayLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -24, 390, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtChiSoCuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChiSoCuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChiSoCuActionPerformed

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
         
    if(txtMaKH.getText().trim().isEmpty() ||
       txtChiSoCu.getText().trim().isEmpty() ||
       txtChiSoMoi.getText().trim().isEmpty()){

        JOptionPane.showMessageDialog(this,"Nhập đầy đủ thông tin!");
        return;
    }

    try{
        int maKH = Integer.parseInt(txtMaKH.getText().trim());
        int chiSoCu = Integer.parseInt(txtChiSoCu.getText().trim());
        int chiSoMoi = Integer.parseInt(txtChiSoMoi.getText().trim());

        if(chiSoMoi < chiSoCu){
            JOptionPane.showMessageDialog(this,"Không hợp lệ");
            return;
        }

        HOA_DON hd = new HOA_DON();
        hd.setMaKH(maKH);
        hd.setChiSoCu(chiSoCu);
        hd.setChiSoMoi(chiSoMoi);

        Hoa_DonDAO dao = new Hoa_DonDAO();

        if(dao.them(hd)){
            JOptionPane.showMessageDialog(this,"Thêm thành công");
            loadHoaDon();
            clearForm();
        }else{
            JOptionPane.showMessageDialog(this,"Thất bại");
        }

    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this,"Chỉ được nhập số!");
    }
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
       int row = tblHoaDon.getSelectedRow();

    if(row == -1){
        JOptionPane.showMessageDialog(this,"Chọn hóa đơn cần sửa");
        return;
    }

    if(txtChiSoCu.getText().trim().isEmpty() ||
       txtChiSoMoi.getText().trim().isEmpty()){

        JOptionPane.showMessageDialog(this,"Không được để trống!");
        return;
    }

    try{
        int maHD = Integer.parseInt(tblHoaDon.getValueAt(row,0).toString());
        int chiSoCu = Integer.parseInt(txtChiSoCu.getText().trim());
        int chiSoMoi = Integer.parseInt(txtChiSoMoi.getText().trim());

        if(chiSoMoi < chiSoCu){
            JOptionPane.showMessageDialog(this,"Không hợp lệ");
            return;
        }

        HOA_DON hd = new HOA_DON();
        hd.setMaHoaDon(maHD);
        hd.setChiSoCu(chiSoCu);
        hd.setChiSoMoi(chiSoMoi);

        Hoa_DonDAO dao = new Hoa_DonDAO();

        if(dao.sua(hd)){
            JOptionPane.showMessageDialog(this,"Sửa thành công");
            loadHoaDon();
        }else{
            JOptionPane.showMessageDialog(this,"Sửa thất bại");
        }

    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this,"Chỉ được nhập số!");
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
       AdminForm f = new AdminForm();
       f.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TaoHDForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtChiSoCu;
    private javax.swing.JTextField txtChiSoMoi;
    private javax.swing.JTextField txtMaKH;
    // End of variables declaration//GEN-END:variables
}
